### ISSUE TITLE
Windows compilation error

### ISSUE THREAD

**Issue by matkuki** [lcrees/pdcurses#1]
Hi,

Installed the package via nimble and tried compiling a simple program:
```nim
import pdcurses
echo "success"
```
file and got the following error:
```
lib\wrappers\pdcurses.nim(43, 10) Error: cannot open 'windows'
```
Specs:
- Windows 10 x64
- Nim Compiler Version 0.17.3 [Windows: i386]

**Comment by matkuki** [comment]
Hey @lcrees ,
Any ideas on how to solve this?
If not, I'll ask around on the forum. Thanks

**Comment by lcrees** [comment]
The `windows` module used to be in the stdlib. It's now available on nimble as `oldwinapi`. Install the version I just committed and tell me if it resolves the issue (I don't have a Windows machine handy).

**Comment by matkuki** [comment]
Previously I had a copy of pdcurses.nim in my *Nim/lib* compiler directory and it used that. I deleted it so now it correctly uses nimble's pdcurses.nim library.

I installed *oldwinapi* through nimble, version is 2.0.0.
Tried it again and got:
```
...\.nimble\pkgs\pdcurses-0.1.1\pdcurses.nim(43, 10) Error: cannot open 'oldwinapi'
```

I changed line 43 in pdcurses.nim to
```
import oldwinapi.windows
```
and then got the following error when compiling:
```
\.nimble\pkgs\oldwinapi-2.0.0\oldwinapi\windows.nim(22905, 10) Error: type mismatch: got (int) but expected 'int32'
```

**Comment by matkuki** [comment]
Changing *oldwinapi*'s windows.nim module line 22905 to:
```
  result = int32(ord(b == h))
```
and line to:
```
  result = int32(ord((int(Status) shr 31) == SEVERITY_ERROR))
```
makes it compile successfully. But when running the example shown in the my first message, it throws this error:
```
could not import: pdc_atrtab
```

**Comment by lcrees** [comment]
It compiled past that point using `wine` on my Mac when I trimmed those variables. 

They're not declared in PDCurses' Win32 header file and they may not be necessary.

See if the newest version compiles.

**Comment by matkuki** [comment]
Yes, it works now.
Thanks @lcrees !
