### ISSUE TITLE
Windows runtime error?

### ISSUE THREAD

**Issue by matkuki** [lcrees/pdcurses#2]
Hi,

I've been trying to get this example to work:
```nim
import pdcurses
import os

var y: cint = 0
var x: cint = 0

discard initscr()
discard printw("Test message") 
getyx(stdscr, y, x)
discard printw("y: %d, x: %d", y , x) # <- prints "y: {some giant number}, x: {some giant number}"
discard move(5, 0) # <- doesn't move the cursor
discard printw("The end")
discard refresh()
discard beep()
sleep(1000)
discard getch() # <- crash / segfault
discard endwin()
```
The application prints "Test messagey: 1953719636, x: 1936026912The end", then crashes at the *getch()* line.

I've tried it with both Nim x86 and x64, in combination with mingw-w64 32/64 bit and msvc 2017 32/64 bit with either PDCurses 3.4 or 3.5, with no difference.

Tested the same program in plain C with dynamic linking to the DLL and it works with all compilers mentioned above.

Any ideas?

**Comment by lcrees** [comment]
Merged
